export const governorates = [
  "البحيرة",
  "الاسكندرية",
  "الفيوم",
  "أسيوط",
  "أسوان",
  "بنى سويف",
  "القاهرة",
  "الدقهلية",
  "دمياط",
  "الغربية",
  "المنيا",
  "الشرقية",
  "السويس",
  "الوادى الجديد",
  "الجيزة",
  "الاسماعيلية",
  "كفر الشيخ",
  "القليوبية",
  "قنا",
  "الاقصر",
  "مطروح",
  "المنوفية",
  "شمال سيناء",
  "بورسعيد",
  "البحر الاحمر",
  "سوهاج",
  "جنوب سيناء",
  "أخرى",
];
export const governoratesEn = [
  "Albehira",
  "Alexandria",
  "AlFayoum",
  "Assiut",
  "Aswan",
  "Bani Suif",
  "Cairo",
  "Dakahlyah",
  "Damietta",
  "ElGharbyah",
  "Elmenia",
  "Elsharkia",
  "Elsuez",
  "Elwadi Elgedid",
  "Giza",
  "Ismalia",
  "Kafr Elsheikh",
  "Kalyoubyah",
  "Kena",
  "Luxor",
  "Matrouh",
  "Menoufya",
  "North Sinai",
  "Port Said",
  "Red Sea",
  "Sohag",
  "South Sinai",
  "Others",
];

export const areas = {
  [governorates[0]]: [
    "مركز ابو المطامير",
    "مركز ابوحمص",
    "مركز الدلنجات",
    "مركز المحمودية",
    "مركز الرحمانية",
    "مركز بدر",
    "قسم دمنهور",
    "مركز دمنهور",
    "قسم غرب النوبارية",
    "مركز حوش عيسى",
    "مركز إدكو",
    "مركز إيتاى البارود",
    "مركز كفر الدوار",
    "قسم كفر الدوار",
    "مركز كوم حمادة",
    "مركز رشيد",
    "مركز شبراخيت",
    "مركز وادى النطرون",
  ],
  [governorates[1]]: [
    "اداره شرطه ميناء الأسكندريه",
    "قسم الدخيلة",
    "قسم أول العامرية",
    "قسم ثان العامرية",
    "قسم العطارين",
    "قسم الجمرك",
    "قسم اللبان",
    "قسم المنشية",
    "قسم أول المنتزة",
    "قسم ثان المنتزة",
    "قسم أول الرمل",
    "قسم ثان الرمل",
    "الساحل الشمالى جزء",
    "قسم باب شرقى",
    "قسم برج العرب",
    "قسم كرموز",
    "مدينه برج العرب الجديده",
    "قسم مينا البصل",
    "قسم محرم بك",
    "قسم سيدى جابر",
  ],
  [governorates[2]]: [
    "مركز الفيوم",
    "قسم الفيوم",
    "مركز أبشواى",
    "مركز أطسا",
    "مدينة الفيوم الجديدة",
    "مركز سنورس",
    "مركز طامية",
    "مركز يوسف الصديق",
  ],
  [governorates[3]]: [
    "مركز أبنوب",
    "قسم ابو تيج",
    "مركز أبوتيج",
    "مركز البدارى",
    "مركز الفتح",
    "مركز الغنايم",
    "مركز القوصية",
    "مركز أسيوط",
    "قسم أول أسيوط",
    "قسم ثان أسيوط",
    "مركز ديروط",
    "مدينة اسيوط الجديدة",
    "مركز منفلوط",
    "مركز ساحل سليم",
    "مركز صدفا",
  ],
  [governorates[4]]: [
    "مركز أبو سنبل",
    "مركز أسوان",
    "قسم اول أسوان",
    "قسم ثان أسوان",
    "مركز دراو",
    "مركز أدفو",
    "مركز كوم امبو",
    "مدينة أسوان الجديدة",
    "مدينة توشكى الجديدة",
    "مركز نصر",
  ],
  [governorates[5]]: [
    "مركز الفشن",
    "مركز الواسطى",
    "قسم بنى سويف",
    "مركز بنى سويف",
    "مركز ببا",
    "مركز أهناسيا",
    "قسم مدينة بنى سويف الجديدة",
    "مركز ناصر",
    "مركز سمسطا",
  ],
  [governorates[6]]: [
    "قسم 15 مايو",
    "قسم عابدين",
    "قسم الدرب الأحمر",
    "قسم عين شمس",
    "قسم الاميريه",
    "قسم الأزبكية",
    "قسم البساتين",
    "قسم الجمالية",
    "قسم الخليفة",
    "قسم المعادي",
    "قسم المرج",
    "قسم المعصره",
    "قسم المطرية",
    "قسم المقطم",
    "قسم الموسكي",
    "قسم أول القاهرة الجديدة",
    "قسم ثان القاهرة الجديدة",
    "قسم ثالث القاهره الجديده",
    "قسم الوايلي",
    "قسم النزهة",
    "قسم الساحل",
    "قسم الشرابية",
    "قسم الشروق",
    "قسم الساحل",
    "قسم أول السلام",
    "قسم ثان السلام",
    "قسم السيدة زينب",
    "قسم التبين",
    "قسم الظاهر",
    "قسم الزمالك",
    "قسم الزاوية الحمراء",
    "قسم الزيتون",
    "قسم باب الشعرية",
    "قسم بولاق",
    "قسم دار السلام",
    "قسم حدائق القبة",
    "قسم حلوان",
    "قسم مدينة نصر أول",
    "قسم ثانى مدينه نصر",
    "قسم مدينة بدر",
    "قسم مصر الجديدة",
    "قسم مصر القديمة",
    "قسم منشأة ناصر",
    "قسم قصر النيل",
    "قسم روض الفرج",
    "قسم شبرا",
    "قسم طره",
  ],
  [governorates[7]]: [
    "مركز أجا",
    "مركز الجمالية",
    "قسم الكردى",
    "مركز المنصورة",
    "قسم اول المنصورة",
    "قسم ثان المنصورة",
    "مركز المنزلة",
    "مركز المطرية",
    "مركز السنبلاوين",
    "مركز بنى عبيد",
    "مركز بلقاس",
    "مركز دكرنس",
    "قسم جمصة",
    "مركز محلة دمنة",
    "مركز منية النصر",
    "قسم ميت غمر",
    "مركز ميت غمر",
    "مركز ميت سلسيل",
    "مركز نبروة",
    "مركز شربين",
    "مركز طلخا",
    "مركز تمى الأمديد",
  ],
  [governorates[8]]: [
    "مركز الزرقا",
    "مركز دمياط",
    "قسم أول دمياط",
    "قسم ثان دمياط",
    "مركز فارسكور",
    "إداره شرطه ميناء دمياط الجديد",
    "مركز كفر البطيخ",
    "مركز كفر سعد",
    "قسم مدينه دمياط الجديده",
    "قسم رأس البر",
  ],
  [governorates[9]]: [
    "مركز المحله الكبرى",
    "قسم أول المحلة الكبرى",
    "قسم ثان المحلة الكبرى",
    "قسم ثالث المحلة الكبرى",
    "مركز السنطة",
    "مركز بسيون",
    "مركز كفر الزيات",
    "مركز قطور",
    "مركز سمنود",
    "مركز طنطا",
    "قسم أول طنطا",
    "قسم ثان طنطا",
    "مركز زفتى",
    "قسم زفتى",
  ],
  [governorates[10]]: [
    "مركز ابو قرقاص",
    "مركز العدوة",
    "مركز المنيا",
    "قسم أول المنيا",
    "قسم ثان المنيا",
    "قسم ثالث المنيا",
    "مركز بنى مزار",
    "مركز دير مواس",
    "مدينة المنيا الجديدة",
    "مركز مغاغة",
    "مركز سمالوط غرب",
    "قسم ملوى",
    "مركز ملوى",
    "مركز مطاى",
    "مركز سمالوط",
  ],
  [governorates[11]]: [
    "مركز أبو حماد",
    "مركز أبوكبير",
    "مركز الحسينية",
    "مركز الأبراهيمية",
    "قسم القنايات",
    "قسم القرين",
    "قسم الصالحية الجديدة",
    "مركز أولاد صقر",
    "قسم اول الزقازيق",
    "قسم ثان الزقازيق",
    "مركز الزقازيق",
    "مركز بلبيس",
    "مركز ديرب نجم",
    "قسم فاقوس",
    "مركز فاقوس",
    "مركز ههيا",
    "مركز كفر صقر",
    "قسم أول مدينة عشرة رمضان",
    "قسم ثان مدينة عشرة رمضان",
    "مركز مشتول السوق",
    "مركز منيا القمح",
    "مركز منشاه ابوعمر",
    "مركز صان الحجر",
  ],
  [governorates[12]]: [
    "قسم الأربعين",
    "قسم الجناين",
    "قسم السويس",
    "قسم عتاقة",
    "قسم فيصل",
    "إدارة شرطة ميناء السويس",
  ],
  [governorates[13]]: [
    "قسم الواحات الخارجة",
    "مركز بلاط",
    "مركز شرطة الداخلة",
    "مركز شرطة الفرافرة",
    "مركز شرطة باريس",
  ],
  [governorates[14]]: [
    "قسم الشيخ زايد",
    "قسم الأهرام",
    "مركز أوسيم",
    "مركز كرداسة",
    "قسم امبابة",
    "مركز إمبابة",
    "قسم الجيزة",
    "مركز الجيزة",
    "قسم الوراق",
    "قسم الواحات البحرية",
    "مركز الصف",
    "قسم العمرانية",
    "قسم الحوامدية",
    "مركز البدرشين",
    "مركز العياط",
    "قسم الدقي",
    "قسم بولاق الدكرور",
    "مركز أطفيح",
    "قسم العجوزة",
    "قسم أول 6 أكتوبر",
    "قسم ثان 6 أكتوبر",
    "قسم ثالث 6 أكتوبر",
    "قسم الطالبيه",
  ],
  [governorates[15]]: [
    "مركز ابو صوير",
    "مركز الاسماعيلية",
    "قسم أول الاسماعيلية",
    "قسم ثان الاسماعيلية",
    "قسم ثالث الاسماعيلية",
    "مركز القنطرة",
    "قسم القنطرة شرق",
    "مركز القصاصين الجديده",
    "مركز التل الكبير",
    "مركز فايد",
  ],
  [governorates[16]]: [
    "مركز البرلس",
    "مركز الحامول",
    "مركز الرياض",
    "قسم بيلا",
    "مركز بيلا",
    "قسم دسوق",
    "مركز دسوق",
    "مركز فوه",
    "مركز كفر الشيخ",
    "قسم أول كفر الشيخ",
    "قسم ثان كفر الشيخ",
    "مركز مطوبس",
    "مركز قلين",
    "مركز سيدى سالم",
  ],
  [governorates[17]]: [
    "قسم الخانكه",
    "مركز الخانكة",
    "قسم الخصوص",
    "مركز القناطر الخيرية",
    "قسم العبور",
    "مركز بنها",
    "قسم اول بنها",
    "قسم ثان بنها",
    "مركز كفر شكر",
    "قسم قها",
    "قسم قليوب",
    "مركز قليوب",
    "قسم أول شبرا الخيمة",
    "قسم ثان شبرا الخيمة",
    "مركز شبين القناطر",
    "مركز طوخ",
  ],
  [governorates[18]]: [
    "مركز أبو طشت",
    "مركز الوقف",
    "مركز دشنا",
    "مركز فرشوط",
    "مدينة قنا الجديدة",
    "مركز نجع حمادى",
    "مركز نقادة",
    "مركز قفط",
    "قسم قنا",
    "مركز قنا",
    "مركز قوص",
  ],
  [governorates[19]]: [
    "مركز القرنه",
    "قسم الأقصر",
    "مركز الأقصر",
    "مركز أرمنت",
    "مركز إسنا",
    "مركز شرطة طيبة",
  ],
  [governorates[20]]: [
    "قسم الضبعة",
    "قسم العلمين",
    "قسم الحمام",
    "قسم النجيله",
    "قسم الساحل الشمالى-جزء",
    "قسم السلوم",
    "قسم مرسى مطروح",
    "قسم سيدى برانى",
    "قسم سيوة",
  ],
  [governorates[21]]: [
    "مركز الباجور",
    "مركز أشمون",
    "مركز الشهداء",
    "مركز بركة السبع",
    "مركز و مدينة السادات",
    "قسم مدينة منوف",
    "مركز منوف",
    "مركز قويسنا",
    "قسم شبين الكوم",
    "مركز شبين الكوم",
    "قسم سرس الليانة",
    "مركز تلا",
  ],
  [governorates[22]]: [
    "قسم أول العريش",
    "قسم ثان العريش",
    "قسم ثالث العريش",
    "قسم رابع العريش",
    "قسم الحسنة",
    "قسم الشيخ زويد",
    "قسم بئر العبد",
    "قسم نخل",
    "قسم رفح",
    "قسم شرطة القسيمة",
    "قسم شرطة رمانة",
  ],
  [governorates[23]]: [
    "قسم شرطة الضواحي",
    "قسم العرب",
    "قسم الجنوب",
    "قسم ثان الجنوب",
    "قسم المناخ",
    "قسم المناصرة",
    "قسم الشرق",
    "قسم شرطة الزهور",
    "قسم بورفؤاد",
    "قسم ثان بورفؤاد",
    "إدارة شرطة ميناء بورسعيد",
    "قسم مبارك - شرق التفريعة",
  ],
  [governorates[24]]: [
    "قسم أول الغردقة",
    "قسم ثان الغردقة",
    "قسم القصير",
    "قسم الشلاتين",
    "قسم حلايب",
    "قسم مرسى علم",
    "قسم رأس غارب",
    "قسم سفاجا",
  ],
  [governorates[25]]: [
    "مركز أخميم",
    "مركز البلينا",
    "قسم الكوثر",
    "مركز المراغة",
    "مركز المنشأة",
    "مركز العسيرات",
    "مركز دار السلام",
    "قسم جرجا",
    "مركز جرجا",
    "مركز جهينة الغربية",
    "مدينة أخميم الجديدة",
    "مدينة سوهاج الجديدة",
    "مركز ساقلته",
    "مركز سوهاج",
    "قسم اول سوهاج",
    "قسم ثان سوهاج",
    "قسم طهطا",
    "مركز طهطا",
    "مركز طما",
  ],
  [governorates[26]]: [
    "قسم أبو رديس",
    "قسم الطور",
    "قسم دهب",
    "قسم نويبع",
    "قسم رأس سدر",
    "قسم سانت كاترين",
    "قسم أول شرم الشيخ",
    "قسم ثان شرم الشيخ",
    "قسم شرطة طابا",
  ],
  [governorates[27]]: ["أخرى"],
};
export const areasEn = {
  [governoratesEn[0]]: [
    "Abu El Matamir",
    "Abu Hummus",
    "El Delengat",
    "Mahmoudiyah",
    "Rahmaniya",
    "Badr",
    "Damanhour",
    "West Nubariyah",
    "Hosh Essa",
    "Edku",
    "Itay El Barud",
    "Kafr El Dawwar",
    "Kom Hamada",
    "Rosetta",
    "Shubrakhit",
    "Natrn Valley",
  ],
  [governoratesEn[1]]: [
    "Port Alexandria Police Dept.",
    "Dekhela",
    "Amreya 1",
    "Amreya 2",
    "Ataren",
    "Gomrok",
    "Labban",
    "Mansheya",
    "Montaza 1",
    "Montaza 2",
    "El Raml 1",
    "El Raml 2",
    "North Coast",
    "Bab Sharqi",
    "Borg El Arab",
    "Karmouz",
    "New Borg El Arab",
    "Port al-Basal",
    "Moharam Bek",
    "Sidi Gaber",
  ],
  [governoratesEn[2]]: [
    "Faiyum",
    "Ibsheway",
    "Itsa",
    "New Faiyum",
    "Sinnuris",
    "Tamiya",
    "Yousef El Seddik",
  ],
  [governoratesEn[3]]: [
    "Abnub",
    "Abu Tig",
    "El Badari",
    "El Fath",
    "El Ghanayem",
    "El Qusiya",
    "Asyut",
    "Asyut 1",
    "Asyut 2",
    "Dairut",
    "New Asyut",
    "Manfalut",
    "Sahel Selim",
    "Sodfa",
  ],
  [governoratesEn[4]]: [
    "Abu Simbel",
    "Aswan",
    "Aswan 1",
    "Aswan 2",
    "Daraw",
    "Edfu",
    "Kom Ombo",
    "New Aswan",
    "New Tushka",
    "Nasser City",
  ],
  [governoratesEn[5]]: [
    "El Fashn",
    "El Wasta",
    "Beni Suef",
    "Biba",
    "Ihnasiya",
    "New Beni Suef",
    "Nasser",
    "Sumusta El Waqf",
  ],
  [governoratesEn[6]]: [
    "15 May City",
    "Abdeen",
    "El Darb El Ahmar",
    "Ain Shams",
    "Amreya",
    "Azbakeya",
    "El Basatin",
    "El Gamaliya",
    "El Khalifa",
    "Maadi",
    "El Marg",
    "El Masara",
    "El Matareya",
    "El Mokattam",
    "El Muski",
    "New Cairo 1",
    "New Cairo 2",
    "New Cairo 3",
    "El Weili",
    "El Nozha",
    "El Sahel",
    "El Sharabiya",
    "El Shorouk",
    "El Segil",
    "El Salam",
    "El Sayeda Zeinab",
    "El Tebbin",
    "El Zaher",
    "Zamalek",
    "El Zawya El Hamra",
    "Zeitoun",
    "Bab El Sharia",
    "Bulaq",
    "Dar El Salam",
    "Hada'iq El Qobbah",
    "Helwan",
    "Nasr City 1",
    "Nasr City 2",
    "Badr City",
    "Heliopolis",
    "Old Cairo",
    "Manshiyat Naser",
    "Qasr El Nil",
    "Rod El Farag",
    "Shubra",
    "Tura",
  ],
  [governoratesEn[7]]: [
    "Aga",
    "El Gamaliya",
    "El Kurdi",
    "El Mansoura",
    "El Mansoura 1",
    "El Mansoura 2",
    "El Manzala",
    "El Matareya",
    "El Senbellawein",
    "Beni Ebeid",
    "Belqas",
    "Dikirnis",
    "Gamasa",
    "Maḥallat Damanah",
    "Minyet El Nasr",
    "Mit Ghamr",
    "Mit Salsil",
    "Nabaroh",
    "Shirbin",
    "Talkha",
    "Timay El Imdid",
  ],
  [governoratesEn[8]]: [
    "El Zarqa",
    "Damietta",
    "Damietta 1",
    "Damietta 2",
    "Faraskur",
    "Police Dept. Port of Damietta",
    "Kafr El Battikh",
    "Kafr Saad",
    "New Damietta",
    "Ras El Bar",
  ],
  [governoratesEn[9]]: [
    "El Mahalla El Kubra",
    "El Mahalla El Kubra 1",
    "El Mahalla El Kubra 2",
    "El Mahalla El Kubra 3",
    "El Sunta",
    "Basyoun",
    "Kafr El Zayat",
    "Kotoor",
    "Samanoud",
    "Tanta",
    "Tanta 1",
    "Tanta 2",
    "Zefta",
  ],
  [governoratesEn[10]]: [
    "Abu Qirqas",
    "El Idwa",
    "Minya",
    "Minya 1",
    "Minya 2",
    "Minya 3",
    "Beni Mazar",
    "Deir Mawas",
    "New Minya",
    "Maghagha",
    "Malawit Gharb",
    "Mallawi",
    "Matai",
    "Samalut",
  ],
  [governoratesEn[11]]: [
    "Abu Hammad",
    "Abu Kebir",
    "El Husseiniya",
    "El Ibrahimiya",
    "El Qanayat",
    "El Qurein",
    "New Salhia",
    "Awlad Saqr",
    "Zagazig 1",
    "Zagazig 2",
    "Zagazig",
    "Bilbeis",
    "Diyarb Negm",
    "Faqous",
    "Hihya",
    "Kafr Saqr",
    "10th of Ramadan City 1",
    "10th of Ramadan City 2",
    "Mashtool El Souk",
    "Minya El Qamh",
    "Minshat Abu Omar",
    "Tanis",
  ],
  [governoratesEn[12]]: [
    "Arbaeen",
    "Ganayen",
    "Suez",
    "Attaka",
    "Faisal",
    "Port Suez Police Department",
  ],
  [governoratesEn[13]]: ["Kharga", "Balat", "Dakhla", "Farafra", "Baris"],
  [governoratesEn[14]]: [
    "Sheikh Zayed City",
    "Al-haram",
    "Ossim",
    "Kerdasa",
    "Imbaba",
    "Giza",
    "El Warraq",
    "El Wahat El Bahariya",
    "El Saff",
    "El Omraniya",
    "El Hawamdeya",
    "El Badrashein",
    "El Ayyat",
    "Dokki",
    "Bulaq",
    "Atfeh",
    "Agouza",
    "6th of October City (1)",
    "6th of October City (2)",
    "6th of October City (3)",
    "El Talbia",
  ],
  [governoratesEn[15]]: [
    "Abu Suwir",
    "Ismailia",
    "Ismailia 1",
    "Ismailia 2",
    "Ismailia 3",
    "El Qantara",
    "El Qantara El Sharqiya",
    "New Kasaseen",
    "Tell El Kebir",
    "Fayid",
  ],
  [governoratesEn[16]]: [
    "Burullus",
    "El Hamool",
    "El Reyad",
    "Bila",
    "Desouk",
    "Fuwa",
    "Kafr el Sheikh",
    "Kafr el Sheikh 1",
    "Kafr el Sheikh 2",
    "Metoubes",
    "Qallin",
    "Sidi Salem",
  ],
  [governoratesEn[17]]: [
    "Khanka",
    "Khusus",
    "El Qanater El Khayreya",
    "El Ubour",
    "Banha",
    "Banha 1",
    "Banha 2",
    "Kafr Shukr[9]",
    "Qaha",
    "Qalyub",
    "Shubra El Kheima 1",
    "Shubra El Kheima 2",
    "Shibin El Qanater",
    "Tukh",
  ],
  [governoratesEn[18]]: [
    "Abu Tesht",
    "El Waqf",
    "Dishna",
    "Farshut",
    "New Qena",
    "Nag Hammadi",
    "Naqada",
    "Gebtu or Coptos",
    "Qena",
    "Qus",
  ],
  [governoratesEn[19]]: ["Qurna", "Luxor", "Armant", "Esna", "Tiba"],
  [governoratesEn[20]]: [
    "El Dabaa",
    "El Alamein",
    "El Hamam",
    "El Negaila",
    "North Coast",
    "Sallum",
    "Mersa Matruh",
    "Sidi Barrani",
    "Siwa Oasis",
  ],
  [governoratesEn[21]]: [
    "El Bagour",
    "Ashmoun",
    "El Shohada",
    "Birket el Sab",
    "Sadat City",
    "Menouf",
    "Quweisna",
    "Shibin el Kom",
    "Sers El Lyan",
    "Tala",
  ],
  [governoratesEn[22]]: [
    "El Arish 1",
    "El Arish 2",
    "El Arish 3",
    "El Arish 4",
    "El Hassana",
    "Sheikh Zuweid",
    "Bir El Abd",
    "Nakhl",
    "Rafah",
    "Shurtet El Qasima",
    "Shurtet Rumana",
  ],
  [governoratesEn[23]]: [
    "El Dawahy",
    "El Arab",
    "El Ganoub",
    "El Ganoub 2",
    "El Manakh",
    "El Manasra",
    "El Sharq",
    "El Zohur",
    "Port Fuad",
    "Port Fuad 2",
    "Police Department Port Said",
    "Mubarak East",
  ],
  [governoratesEn[24]]: [
    "Hurghada 1",
    "Hurghada 2",
    "El Qusair",
    "Shalateen",
    "Halaib",
    "Marsa Alam",
    "Ras Gharib",
    "Safaga",
  ],
  [governoratesEn[25]]: [
    "Akhmim",
    "El Balyana",
    "El Kawtar",
    "El Maragha",
    "El Munsha",
    "Aserat",
    "Dar El Salam",
    "Girga",
    "Juhaynah West",
    "New Akhmim",
    "New Sohag",
    "Saqultah",
    "Sohag",
    "Sohag 1",
    "Sohag 2",
    "Tahta",
    "Tima",
  ],
  [governoratesEn[26]]: [
    "Abu Radis (incl. Abu Zenima)",
    "El Tor",
    "Dahab",
    "Nuweiba",
    "Ras Sidr",
    "Saint Catherine",
    "Sharm El Sheikh 1",
    "Sharm El Sheikh 2",
    "Taba",
  ],
  [governoratesEn[27]]: ["Others"],
};

export const residentialStatuses = ["تمليك", "منزل عائلي", "إيجار"];
export const residentialStatusesEn = ["Fully Owned", "Family House", "Rented"];

export const maritalStatus = ["اعزب", "متزوج / مُطلق", "أرمل / أرملة"];
export const maritalStatusEn = [
  "Single",
  "Married / Divorced",
  "Widow / Widower",
];

export const dependentsNum = [
  "لا يوجد",
  "شخص واحد",
  "شخصان",
  "ثلاث اشخاص او اكثر",
];
export const dependentsNumEn = [
  "No one",
  "1 person",
  "2 persons",
  "3 or more persons",
];

export const employmentStatuses = [
  "موظف",
  "صاحب عمل",
  "عمل مُستقل",
  "بدون عمل",
];
export const employmentStatusesEn = [
  "Salaried Employee",
  "Self Employed (Business Ownership)",
  "Free Lancer",
  "Unemployed",
];

export const employmentSectors = {
  [employmentStatuses[0]]: [
    "البنوك / الشركات المالية",
    "موظف حكومي",
    "ضابط شرطة / جيش",
    "القضاء",
    "الهندسة والتصنيع",
    "وكالات الدعاية والتسويق",
    "السياحة والفنادق",
    "مستشفيات / عيادات / أدوية / رعاية صحية",
    "تكنولوجيا المعلومات",
    "خدمات تعليمية",
    "العقارات والبناء",
    "وزارة الخارجية",
    "الصحافة والاعلام",
    "أخرى - شركة محلية",
    "أخرى - شركة متعددة الجنسيات",
  ],
  [employmentStatuses[1]]: [
    "مستشفيات / عيادات / أدوية / رعاية صحية",
    "الشركات المالية",
    "الهندسة والتصنيع",
    "وكالات الدعاية والتسويق",
    "السياحة والفنادق",
    "تكنولوجيا المعلومات",
    "خدمات تعليمية",
    "العقارات والبناء",
    "الصحافة والاعلام",
    "أخرى - شركة محلية",
    "أخرى - شركة متعددة الجنسيات",
  ],
  [employmentStatuses[2]]: [
    "الاستشارات القانونية",
    "عيادات / صيدليات / رعاية صحية",
    "البرمجة وتطوير البرمجيات",
    "تسويق رقمى و وسائل التواصل الاجتماعي",
    "تصميم الجرافيك / المواقع الالكترونية",
    "أخرى",
  ],
  [employmentStatuses[3]]: ["لا شئ"],
};

export const employmentSectorsEn = {
  [employmentStatusesEn[0]]: [
    "Banks / Financial Firms",
    "Governmental Employee",
    "Police / Army Officer",
    "Judiciary",
    "Engineering & Manufacturing",
    "Advertising/Marketing Agencies",
    "Tourism & Hotels",
    "Hospitals / Clinics / Pharmaceuticals / Healthcare",
    "Information Technology",
    "Educational Services",
    "Real-estate and Construction",
    "Ministry of Foreign Affairs",
    "Press and Media",
    "Others - Local Company",
    "Others - Multinational Company",
  ],
  [employmentStatusesEn[1]]: [
    "Hospitals / Clinics / Pharmaceuticals / Healthcare",
    "Financial Firms",
    "Engineering & Manufacturing",
    "Advertising/Marketing Agencies",
    "Tourism & Hotels",
    "Information Technology",
    "Educational Services",
    "Real-estate and Construction",
    "Press and Media",
    "Others - Local Company",
    "Others - Multinational Company",
  ],
  [employmentStatusesEn[2]]: [
    "Legal Advisory",
    "Clinics / Pharmacies / Healthcare",
    "Programming And Software Development",
    "Social Media & Digital Marketing",
    "Graphic / Web Design",
    "Others",
  ],
  [employmentStatusesEn[3]]: ["None"],
};

export const jobTitles = {
  [`موظف${employmentSectors["موظف"][0]}`]: [
    "مصرفى / موظف",
    "محاسب",
    "محلل مالى",
    "مدير فرع",
    "مدير منطقة",
    "مدير ادارة",
    "رئيس قطاع",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "موظف بمركز الاتصال",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "عامل / فنى",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][1]}`]: [
    "موظف",
    "اخصائي",
    "مشرف",
    "محاسب",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "وكيل وزارة",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "عامل / فنى",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][2]}`]: [
    "لواء",
    "عميد",
    "عقيد",
    "مقدم",
    "رائد",
    "نقيب",
    "ملازم أول",
    "ملازم ثان",
    "امين شرطة / ضابط صف",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][3]}`]: [
    "وكيل نيابة",
    "رئيس نيابة",
    "مستشار قضائى",
    "قاضى",
    "نائب رئيس محكمة",
    "رئيس محكمة",
    "موظف",
    "موظف إدخال بيانات",
    "اخصائي",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][4]}`]: [
    "مهندس",
    "عامل / فنى",
    "مشرف",
    "اخصائي",
    "أخصائى / مهندس ضبط جودة",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "محاسب",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][5]}`]: [
    "مصمم جرافيك",
    "مدير فنى",
    "مصور فوتوغرافي",
    "اخصائى تسويق",
    "مدير تسويق",
    "مهندس",
    "موظف",
    "موظف بمركز الاتصال",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "محاسب",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][6]}`]: [
    "مرشد سياحى",
    "أخصائى حجز",
    "علاقات عامة",
    "موظف إستقبال",
    "شيف",
    "مندوب مبيعات",
    "مهندس",
    "موظف",
    "موظف بمركز الاتصال",
    "محاسب",
    "سائق",
    "خدمات معاونة",
    "موظف أمن",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][7]}`]: [
    "ممثل طبى",
    "طبيب بشري",
    "طبيب اسنان",
    "ممرض",
    "متخصص خدمات طبية",
    "محاسب",
    "موظف إستقبال",
    "علاقات عامة",
    "مندوب مبيعات",
    "موظف بمركز الاتصال",
    "موظف",
    "موظف أمن",
    "سائق",
    "خدمات معاونة",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][8]}`]: [
    "متخصص في تكنولوجيا المعلومات",
    "مطور برامج",
    "مدير تكنولوجيا المعلومات",
    "مصمم جرافيك",
    "مهندس",
    "مهندس بيانات",
    "أخصائي أمن المعلومات",
    "مندوب مبيعات",
    "موظف بمركز الاتصال",
    "محاسب",
    "موظف",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "موظف أمن",
    "سائق",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][9]}`]: [
    "مدرس بالمدرسة",
    "ناظر مدرسة",
    "موظف",
    "موظف إدخال بيانات",
    "مُعيد بالجامعة",
    "مدرس مساعد جامعى",
    "مدرس جامعى",
    "استاذ مساعد جامعى",
    "استاذ جامعى",
    "اخصائي",
    "موظف أمن",
    "محاسب",
    "سائق",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][10]}`]: [
    "مهندس",
    "مستشار عقارات",
    "سمسار عقارات",
    "مندوب مبيعات",
    "قائد فريق المبيعات",
    "موظف بمركز الاتصال",
    "موظف إدخال بيانات",
    "موظف",
    "علاقات عامة",
    "موظف إستقبال",
    "محاسب",
    "سائق",
    "خدمات معاونة",
    "موظف أمن",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][11]}`]: [
    "ملحق",
    "سكرتير ثالث",
    "سكرتير ثان",
    "سكرتير اول",
    "مستشار",
    "وزير مفوض",
    "سفير",
    "محلق ادارى",
    "موظف",
    "موظف إدخال بيانات",
    "محاسب",
    "سائق",
    "خدمات معاونة",
    "موظف أمن",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][12]}`]: [
    "صحفى",
    "مذيع",
    "مراسل",
    "منسق الصحافة ووسائل التواصل الاجتماعي",
    "اخصائى تسويق",
    "مدير تسويق",
    "مصور",
    "مصمم جرافيك",
    "مدير فنى",
    "مصور فوتوغرافي",
    "موظف",
    "موظف بمركز الاتصال",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "محاسب",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][13]}`]: [
    "محاسب",
    "محلل مالى",
    "موظف",
    "اخصائي",
    "مشرف",
    "اخصائى موارد بشرية",
    "اخصائى تسويق",
    "متخصص في تكنولوجيا المعلومات",
    "مهندس",
    "مندوب مبيعات",
    "قائد فريق المبيعات",
    "موظف بمركز الاتصال",
    "موظف إدخال بيانات",
    "موظف",
    "علاقات عامة",
    "موظف إستقبال",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "عامل / فنى",
    "أخري",
  ],
  [`موظف${employmentSectors["موظف"][14]}`]: [
    "محاسب",
    "محلل مالى",
    "موظف",
    "اخصائي",
    "مشرف",
    "اخصائى موارد بشرية",
    "اخصائى تسويق",
    "متخصص في تكنولوجيا المعلومات",
    "مهندس",
    "مندوب مبيعات",
    "قائد فريق المبيعات",
    "موظف بمركز الاتصال",
    "موظف إدخال بيانات",
    "موظف",
    "علاقات عامة",
    "موظف إستقبال",
    "رئيس قسم",
    "مدير ادارة",
    "مدير قطاع",
    "مدير عام",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "خدمات معاونة",
    "موظف أمن",
    "سائق",
    "عامل / فنى",
    "أخري",
  ],
  // TODO: Continue for [1][...]
  [`صاحب عمل${employmentSectors["صاحب عمل"][0]}`]: [
    "صاحب صيدلية",
    "صاحب عيادة",
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][1]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][2]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][3]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][4]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][5]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][6]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][7]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][8]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][9]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  [`صاحب عمل${employmentSectors["صاحب عمل"][10]}`]: [
    "صاحب منشأة",
    "شريك",
    "صاحب منشأة ومدير",
    "شريك ومدير",
    "شريك متضامن",
    "شريك موصى",
    "رئيس التنفيذى",
    "عضو مجلس ادارة",
    "رئيس مجلس ادارة",
    "أخري",
  ],
  // TODO: Continue for [2][...]
  [`عمل مُستقل${employmentSectors["عمل مُستقل"][0]}`]: [
    "محامى",
    "مستشار قانونى",
    "مستشار الضرائب",
    "مساعد محامى",
    "أخري",
  ],
  [`عمل مُستقل${employmentSectors["عمل مُستقل"][1]}`]: [
    "صيدلاني",
    "طبيب بشري",
    "طبيب اسنان",
    "ممرض",
    "ممثل طبى",
    "أخري",
  ],
  [`عمل مُستقل${employmentSectors["عمل مُستقل"][2]}`]: [
    "متخصص في تكنولوجيا المعلومات",
    "مطور برامج",
    "مبرمج",
    "مهندس برمجيات",
    "مطور تطبيقات",
    "أخري",
  ],
  [`عمل مُستقل${employmentSectors["عمل مُستقل"][3]}`]: [
    "أخصائي وسائل التواصل الاجتماعي",
    "أخصائي التسويق الرقمي",
    "صانع محتوى",
    "مدير تسويق",
    "مدون",
    "أخري",
  ],
  [`عمل مُستقل${employmentSectors["عمل مُستقل"][4]}`]: [
    "مصمم جرافيك",
    "مدير فنى",
    "مصور فوتوغرافي",
    "مصور فيديو",
    "محرر فيديو",
    "مصمم مواقع الكترونية",
    "أخري",
  ],
  [`عمل مُستقل${employmentSectors["عمل مُستقل"][5]}`]: [
    "مندوب مبيعات",
    "موظف إدخال بيانات",
    "مترجم",
    "محامى",
    "مستشار قانونى",
    "مستشار الضرائب",
    "صيدلاني",
    "طبيب بشري",
    "طبيب اسنان",
    "مصمم جرافيك",
    "أخصائي وسائل التواصل الاجتماعي",
    "أخصائي التسويق الرقمي",
    "مطور برامج",
    "أخري",
  ],
  // TODO Continue for [3][...]
  [`بدون عمل${employmentSectors["بدون عمل"][0]}`]: ["لا شئ"],
};
export const jobTitlesEn = {
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][0]}`]: [
    "Banker / Clerk",
    "Accountant",
    "Financial Analyst",
    "Branch Manager",
    "Regional Manager",
    "Department Manager",
    "Head of Division",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Call Center Agent",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Worker / Technician",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][1]}`]: [
    "Clerk",
    "Specialist",
    "Supervisor",
    "Accountant",
    "Department Head",
    "Division Head",
    "General Manager",
    "Deputy Minister",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Worker / Technician",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][2]}`]: [
    "Major General",
    "Brigadier-General",
    "Colonel",
    "Lieutenant-Colonel",
    "Major",
    "Captain",
    "First-Lieutenant",
    "Second-Lieutenant",
    "Police Secretary / Sub-Officer",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][3]}`]: [
    "Prosecutor",
    "Chief Prosecutor",
    "Attorney General",
    "Judge",
    "Vice President of Court",
    "Chief of Court",
    "Clerk",
    "Data Entry Clerk",
    "Specialist",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][4]}`]: [
    "Engineer",
    "Worker / Technician",
    "Supervisor",
    "Specialist",
    "Quality Control Specialist / Engineer",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Accountant",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][5]}`]: [
    "Graphic Designer",
    "Art Director",
    "Photographer",
    "Marketing Specialist",
    "Marketing Manager",
    "Engineer",
    "Clerk",
    "Call Center Agent",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Accountant",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][6]}`]: [
    "Tour Guide",
    "Reservation Specialist",
    "Public Relations",
    "Receptionist",
    "Chef",
    "Sales Representative",
    "Engineer",
    "Clerk",
    "Call Center Agent",
    "Accountant",
    "Driver",
    "Support Services",
    "Secuirty Officer",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][7]}`]: [
    "Medical Representative",
    "Doctor",
    "Dentist",
    "Nurse",
    "Medical Services Specialist",
    "Accountant",
    "Receptionist",
    "Public Relations",
    "Sales Representative",
    "Call Center Agent",
    "Clerk",
    "Secuirty Officer",
    "Driver",
    "Support Services",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][8]}`]: [
    "IT Specialist",
    "Software Developer",
    "IT Manager",
    "Graphic Designer",
    "Engineer",
    "Data Engineer",
    "Information Security Specialist",
    "Sales Representative",
    "Call Center Agent",
    "Accountant",
    "Clerk",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Secuirty Officer",
    "Driver",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][9]}`]: [
    "School Teacher",
    "School Master",
    "Clerk",
    "Data Entry Clerk",
    "Teaching Assistant",
    "Assistant Lecturer",
    "Lecturer",
    "Assistant Professor",
    "Professor",
    "Specialist",
    "Secuirty Officer",
    "Accountant",
    "Driver",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][10]}`]: [
    "Engineer",
    "Property Consultant",
    "Real-estate Broker",
    "Sales Representative",
    "Sales Team leader",
    "Call Center Agent",
    "Data Entry Clerk",
    "Clerk",
    "Public Relations",
    "Receptionist",
    "Accountant",
    "Driver",
    "Support Services",
    "Secuirty Officer",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][11]}`]: [
    "Attache",
    "Third Secretary",
    "Second Secretary",
    "First Secretary",
    "Councellor",
    "Minister Councellor",
    "Ambassador",
    "Administrative Attache",
    "Clerk",
    "Data Entry Clerk",
    "Accountant",
    "Driver",
    "Support Services",
    "Secuirty Officer",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][12]}`]: [
    "Journalist",
    "Broadcaster",
    "Reporter",
    "Press & Social Media Coordinator",
    "Marketing Specialist",
    "Marketing Manager",
    "Cameraman",
    "Graphic Designer",
    "Art Director",
    "Photographer",
    "Clerk",
    "Call Center Agent",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Accountant",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][13]}`]: [
    "Accountant",
    "Financial Analyst",
    "Clerk",
    "Specialist",
    "Supervisor",
    "HR Specialist",
    "Makreting Specialist",
    "IT Specialist",
    "Engineer",
    "Sales Representative",
    "Sales Team leader",
    "Call Center Agent",
    "Data Entry Clerk",
    "Clerk",
    "Public Relations",
    "Receptionist",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Worker / Technician",
    "Other",
  ],
  [`Salaried Employee${employmentSectorsEn["Salaried Employee"][14]}`]: [
    "Accountant",
    "Financial Analyst",
    "Clerk",
    "Specialist",
    "Supervisor",
    "HR Specialist",
    "Makreting Specialist",
    "IT Specialist",
    "Engineer",
    "Sales Representative",
    "Sales Team leader",
    "Call Center Agent",
    "Data Entry Clerk",
    "Clerk",
    "Public Relations",
    "Receptionist",
    "Section Head",
    "Department Head",
    "Division Head",
    "General Manager",
    "Chief Executive Officer",
    "Member of the Board of Directors",
    "Chariman",
    "Support Services",
    "Secuirty Officer",
    "Driver",
    "Worker / Technician",
    "Other",
  ],
  // TODO: Continue for [1][...]
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][0]}`]:
    [
      "Pharmacy Owner",
      "Clinic Owner",
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][1]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][2]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][3]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][4]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][5]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][6]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][7]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][8]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][9]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  [`Self Employed (Business Ownership)${employmentSectorsEn["Self Employed (Business Ownership)"][10]}`]:
    [
      "Entity Owner",
      "Partner",
      "Entity Owner & Manager",
      "Partner & Manager",
      "Active Partner",
      "Dormant Partner",
      "Chief Executive Officer",
      "Member of the Board of Directors",
      "Chariman",
      "Other",
    ],
  // TODO: Continue for [2][...]
  [`Free Lancer${employmentSectorsEn["Free Lancer"][0]}`]: [
    "Lawyer",
    "Legal Counsel",
    "Tax Counsel",
    "Assistant Lawyer",
    "Other",
  ],
  [`Free Lancer${employmentSectorsEn["Free Lancer"][1]}`]: [
    "Pharmacist",
    "Doctor",
    "Dentist",
    "Nurse",
    "Medical Representative",
    "Other",
  ],
  [`Free Lancer${employmentSectorsEn["Free Lancer"][2]}`]: [
    "IT Specialist",
    "Software Developer",
    "Programmer",
    "Software Engineer",
    "Mobile Application Developer",
    "Other",
  ],
  [`Free Lancer${employmentSectorsEn["Free Lancer"][3]}`]: [
    "Social Media Specialist",
    "Digital Marketing Specialist",
    "Content Creator",
    "Marketing Manager",
    "Blogger",
    "Other",
  ],
  [`Free Lancer${employmentSectorsEn["Free Lancer"][4]}`]: [
    "Graphic Designer",
    "Art Director",
    "Photographer",
    "Videographer",
    "Video Editor",
    "Web Designer",
    "Other",
  ],
  [`Free Lancer${employmentSectorsEn["Free Lancer"][5]}`]: [
    "Sales Representative",
    "Data Entry Clerk",
    "Translator",
    "Lawyer",
    "Legal Counsel",
    "Tax Counsel",
    "Pharmacist",
    "Doctor",
    "Dentist",
    "Graphic Designer",
    "Social Media Specialist",
    "Digital Marketing Specialist",
    "Software Developer",
    "Other",
  ],
  // TODO Continue for [3][...]
  [`Unemployed${employmentSectorsEn["Unemployed"][0]}`]: ["None"],
};

export const workYears = [
  "اقل من سنة",
  "بين سنة",
  "بين سنتان وخمس سنوات",
  "اكثر من خمس سنوات",
  "متقاعد / بدون عمل",
];
export const workYearsEn = [
  "Less than 1 year",
  "Between 1 and 2 years",
  "Between 2 and 5 years",
  "More than 5 years",
  "Retired / Unemployed",
];

export const referralTypes = [
  "العائلة والأصدقاء",
  "الفرع",
  "كشك",
  "وسائل التواصل الاجتماعي",
  "صديق",
];

export const referralTypesEn = [
  "Family and Friends",
  "Branch",
  "Booth",
  "Social Media",
  "Friend",
];
