import { PERMISSIONS } from 'react-native-permissions';

export const readArrayOfPermissionsListIOS = [
  PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY,
  PERMISSIONS.IOS.CONTACTS,
  PERMISSIONS.IOS.REMINDERS,
];

export const readArrayOfPermissionsListAndroid = [
  PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
  PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION,
  PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION,
  // PERMISSIONS.ANDROID.READ_CONTACTS,
  // PERMISSIONS.ANDROID.GET_ACCOUNTS,
  PERMISSIONS.ANDROID.NEARBY_WIFI_DEVICES,
  PERMISSIONS.ANDROID.READ_SMS,
  PERMISSIONS.ANDROID.SEND_SMS,
  PERMISSIONS.ANDROID.RECEIVE_SMS,
  // PERMISSIONS.ANDROID.READ_CALL_LOG,
  // PERMISSIONS.ANDROID.WRITE_CALL_LOG,
  PERMISSIONS.ANDROID.READ_PHONE_STATE,
  PERMISSIONS.ANDROID.READ_PHONE_NUMBERS,
  // PERMISSIONS.ANDROID.WRITE_CONTACTS,
  PERMISSIONS.ANDROID.CALL_PHONE,
];
