/* eslint-disable max-len */
export const governorates = [
  'القاهرة',
  'الجيزة',
  'الإسكندرية',
  'القليوبية',
  'بورسعيد',
  'الشرقية',
  'البحر الأحمر',
  'المنوفية',
  'قنا',
  'الدقهلية',
  'الفيوم',
  'الغربية',
  'بني سويف',
  'الأقصر',
  'الاسماعيلية',
  'جنوب سيناء',
  'المنيا',
  'كفر الشيخ',
  'اسوان',
  'البحيرة',
  'دمياط',
  'شمال سيناء',
  'السويس',
  'مطروح',
  'سوهاج',
  'أسيوط',
  'الوادى الجديد',
  'أخرى'
];
export const governoratesEn = [
  'Cairo',
  'Giza',
  'Alexandria',
  'Al Qalyubia',
  'Port Said',
  'Ash Sharqia',
  'Red Sea',
  'Menofia',
  'Qena',
  'Dakahlia',
  'Faiyum',
  'Gharbia',
  'Beni Suef ',
  'Luxor',
  'Ismailia',
  'South Sinai',
  'Minya',
  'Kafr El Sheikh',
  'Aswan',
  'El Beheira',
  'Damietta',
  'North Sinai',
  'Suez',
  'Matrouh',
  'Souhag',
  'Asyut',
  'El Wady El Gdeed ',
  'Others'
];
export const areasEn = {
  [governoratesEn[0]]: [
    'Nasr City',
    'Heliopolis',
    'El Nozha',
    'Shubra',
    'Abbasia',
    'Al Waili',
    'Daher',
    'Al Darrasa',
    'Ain Shams',
    'Manial',
    'Helmeyat El Zaytoun',
    'Hadayeq El Zeitoun',
    'Hadaeq Al Qubbah',
    'Zamalek',
    'Maadi',
    'Downtown',
    'El Mukkatam',
    'Abdeen',
    'Ramses',
    'Attaba',
    'Helwan',
    'Bulaq',
    'Shubra Al Khaymah',
    'Ash Sharabiyyah',
    'Old Cairo',
    'Garden City',
    'Rod El Farag',
    'El Shorouk City',
    'Sahel District',
    'Hadiq El Qobbah',
    'Dar El-Salam',
    'El-Zawya El-Hamraa',
    'Al Rehab',
    'El-Khalifa',
    'El Katameya',
    'El Obour City',
    'Al Kasr Al Aini',
    'El-Sayeda Zainab',
    'El Basatin',
    'El-Gamaleya',
    'El-Darb El-Ahmar',
    'Al Matariyyah',
    'El Mousky',
    'Al Amiriyyah',
    'Al Azbakeya',
    '15th of May City',
    'Al Mansouria',
    'Al Marj',
    'The Fifth Settlement',
    'Jazīrat Warrāq al Ḩaḑar',
    'Hadayek Helwan',
    'Al Fagalah',
    'El-Salam City',
    'Hammamat El Kobba',
    'Al Sayeda Nafisa',
    'El-Zaytoun',
    'New Cairo',
    'Bab Al Louq',
    'Bab Ash Shariyah',
    'Qasr El Nil',
    'Al Munirah',
    'Al-Helmiya Al-Gdeda',
    'Obour City',
    'Monshaet Nasser',
    'Bab Al Khalq',
    'El-Qobba Bridge',
    'Al Tbin',
    'Saray El-Kobba',
    'Al Herafieen',
    'El Salam',
    'Huckstep',
    'Al-Azhar',
    'Qabaa',
    'Badr City'
  ],
  [governoratesEn[1]]: [
    'Al Agouza',
    'Dokki',
    'Mohandseen',
    'Faisal',
    'Al Haram',
    '6th of October City',
    'Kerdasah',
    'Al Omraneyah',
    'El Giza',
    'Imbaba',
    'Shubra Ment',
    'Al Badrashin',
    'Ausim',
    'Boulaq Ad Dakrour',
    'Atfih',
    'Warraq',
    'El-Hawamdeyya',
    'Ard El Lewa',
    'El-Saf City'
  ],
  [governoratesEn[2]]: [
    'El Soyof',
    'Sultan Hussein',
    'El Laban',
    'King Marriot',
    'Ras at Tin',
    'Bacos',
    'Toson',
    'Karmus',
    'Manshiyat Nuzha',
    'Al Mamurah',
    'Schutz',
    'Khorshed ',
    'Cleopatra',
    'El Raml',
    'El Nobaria',
    'Amerya',
    'Abu Qir',
    'Victoria',
    'El Manshya',
    'Al Max',
    'Borg Al Arab',
    'Al Attarin',
    'Bab El-Sharq',
    'Mina El-Basal',
    'Saba Basha',
    'Kafr Abdu',
    'Zezenia',
    'Mostafa Kamel',
    'Luran',
    'Camp Chezar',
    'Moharam Bek',
    'Montaza',
    'Azarita',
    'Sidi Gaber',
    'El Hadra El Gadida',
    'Ad Dakhilah',
    'Miami',
    'Al Hanouvel',
    'Smouha',
    'Asafra',
    'Gianaclis',
    'Sporting',
    'Bolkly',
    'Al Ibrahimeyah',
    'Sidi Bishr',
    'El-Mandara',
    'San Stefano',
    'Roushdy',
    'El Gomrok',
    'El Raml Station',
    'El-Agamy',
    'Flemig',
    'Shatby',
    'Glim'
  ],
  [governoratesEn[3]]: [
    'Abu Zabal',
    'Bahtim',
    'Kafr Shokr',
    'Abu Zabal',
    'Shubra Al Khaymah',
    'Shibin Al Qanater',
    'Tukh',
    'Qalyoub',
    'Al Khankah',
    'Banha',
    'Al Qanatir Al Khayriyyah'
  ],
  [governoratesEn[4]]: ['Port Said'],
  [governoratesEn[5]]: [
    '10th of Ramadan City',
    'Zagazig',
    'Faqus',
    'Belbes',
    'Abu Hammad',
    'Minya Al Qamh',
    'Dyarb Negm',
    'Kafr Abrash',
    'El Husseiniya',
    'Mashtul as Suq',
    'Hihya',
    'Abu Kibir',
    'Basyoun'
  ],
  [governoratesEn[6]]: ['Hurghada', 'Safaga', 'Ras Ghareb', 'EL Kaser', 'Alam Port', 'Shalatin', 'Halayb City'],
  [governoratesEn[7]]: [
    'Quwaysna',
    'El Sadat City',
    'Birkat as SAB',
    'Al Shohadaa',
    'Minuf',
    'Ashmun',
    'Shebeen El-Kom',
    'Tala',
    'Al-Bagour Center'
  ],
  [governoratesEn[8]]: [
    'Qous Center',
    'Kaft Center',
    'Naqada Center ',
    'Qena Center',
    'Waqf Center',
    'Abu Tesht Center',
    'Farshoot Center',
    'Naga Hamady Center',
    'Deshna Center'
  ],
  [governoratesEn[9]]: [
    'Aga',
    'Al Jamaliyah',
    'El Satamony',
    'Al Senbilawin',
    'El Kurdy',
    'Al-Matareya Center',
    'Al Manzalah',
    'Mansoura',
    'Belkas',
    'Bani Ebeed',
    'Tamy El Amdeed',
    'Sharbeen',
    'Talkha',
    'Mahala Damna',
    'Menyet El-Nasr City',
    'Nabroh',
    'Mit Ghamr',
    'Mit Salsabeel'
  ],
  [governoratesEn[10]]: ['Faiyum', 'Snouras', 'Ebshway', 'Etsa', 'Tamya', 'Youssef El Sedeeq'],
  [governoratesEn[11]]: [
    'Tanta',
    'Kafr El-Zayat',
    'El-Mahalla El-Kubra',
    'As Santah',
    'Zifta',
    'Madinet Qotour',
    'Basyoun',
    'Samannoud'
  ],
  [governoratesEn[12]]: [
    'El Wasty',
    'Naser',
    'Ehnasya',
    'Beba',
    'Semsta',
    'El Foshn',
    'Beni Suef El Gdeda',
    'Beni Suef'
  ],
  [governoratesEn[13]]: ['Luxor'],
  [governoratesEn[14]]: [
    'Ismailia',
    'El Tal Elkbeer',
    'Fayed',
    'East Elkantara',
    'West Elkantara',
    'Abu Seer',
    'El Kasaseen'
  ],
  [governoratesEn[15]]: [
    'Nuweiba',
    'Sharm El-Shaikh',
    'Abu Radees',
    'Abu Zaneema',
    'Taba',
    'Ras Seder',
    'Saint Catherin',
    'Dahab',
    'El Tor Sinai'
  ],
  [governoratesEn[16]]: [
    'Maghagha',
    'Bani Mazar',
    'Motay',
    'Samalot',
    'Menya City',
    'Abu Kerkaas',
    'Malwy',
    'Der Mowuaas',
    'El Adwa  '
  ],
  [governoratesEn[17]]: [
    'Mutubis',
    'Fuh',
    'Kaleen',
    'Kafer Elshiekh Center',
    'Dusuq',
    'Bella',
    'El Hamool',
    'Elborolos',
    'Sedy Salem',
    'El Ryad Center'
  ],
  [governoratesEn[18]]: ['Aswan', 'Drawo', 'Kom Ambo', 'Naser Elnoba', 'Edfu'],
  [governoratesEn[19]]: [
    'Etai Al barood',
    'Kum Hamada',
    'Al Nubarya',
    'Kafer Al Dawar',
    'Al Rahmany',
    'Abu Al Matameer',
    'Edco`',
    'Rasheed Center',
    'Kafer El',
    'Bader Center',
    'Natroun Valley Center',
    'Damanhour',
    'Eisa Housh',
    'Abu Hems Center',
    'Shabrakheet',
    'Al Dalanajat',
    'Mahmoudya Center'
  ],
  [governoratesEn[20]]: ['Kafer Al Batikh', 'Al Zarqa', 'Farskur', 'Damietta', 'Kafer Saad'],
  [governoratesEn[21]]: ['Bir El Abd', 'Nakhl', 'El Hasnah', 'El Areesh', 'El Shiekh Zwayd', 'Rafah'],
  [governoratesEn[22]]: ['El Suez', 'Al Arbaein', 'Ataka', 'El Ganayen', 'Faisal'],
  [governoratesEn[23]]: [
    'Siwa Center',
    'Saloum Center',
    'Berany Center',
    'El Negela Center',
    'Marsa Matrouh Center',
    'Dabaa Center',
    'Alameeen Center',
    'Hamaam Center'
  ],
  [governoratesEn[24]]: [
    'Al Balina',
    'Gerga',
    'Al Munshaa',
    'Juhayna',
    'Tama',
    'Tahta',
    'Al Maragha',
    'Saqilta',
    'Dar El Salam',
    'Akhmim',
    'Sohag Center'
  ],
  [governoratesEn[25]]: [
    'Dayrut',
    'Elkoosya',
    'Abnub',
    'Munfilut',
    'Asyut',
    'Sadafaan',
    'Al badary',
    'Sleem Cost',
    'Abu Teeg',
    'Alghanaym'
  ],
  [governoratesEn[26]]: ['El Kharga', 'Paris', 'Mot', 'Balat', 'El Frafra'],
  [governoratesEn[27]]: ['Others']
};
export const areas = {
  [governorates[0]]: [
    'مدينه نصر',
    'مصر الجديده',
    'النزهه',
    'شبرا',
    'العباسيه',
    'الوايلى',
    'الظاهر',
    'الدراسه',
    'عين شمس',
    'المنيل',
    'حلميه الزيتون',
    'حدائق الزيتون',
    'حدائق القبه',
    'الزمالك',
    'المعادى',
    'وسط المدينه',
    'المقطم',
    'عابدين',
    'رمسيس',
    'العتبه',
    'حلوان',
    'بولاق ابو العلا',
    'شبرا الخيمة',
    'الشرابية',
    'مصر القديمة',
    'جاردن سيتي',
    'روض الفرج',
    'الشروق',
    'الساحل',
    'حدائق القبة',
    'دار السلام',
    'الزاوية الحمراء',
    'الرحاب',
    'الخليفة',
    'القطامية',
    'العبور',
    'القصر العيني',
    'السيدة زينب',
    'البساتين',
    'الجمالية',
    'الدرب الاحمر',
    'المطرية',
    'الموسكى',
    'الاميرية',
    'الازبكية',
    '15 مايو',
    'المنصورية',
    'المرج',
    'التجمع الخامس',
    'الوراق',
    'حدائق حلوان',
    'الفجالة',
    'مدينة السلام',
    'حمامات القبة',
    'السيدة نفيسة',
    'الزيتون',
    'القاهرة الجديدة',
    'باب اللوق',
    'باب الشعرية',
    'قصر النيل',
    'المنيره',
    'الحلمية الجديدة',
    'مدينة العبور',
    'منشاه ناصر',
    'باب الخلق',
    'كوبرى القبه',
    'التبين',
    'سراى القبة',
    'الحرفيين',
    'السلام',
    'الهايكستب',
    'الأزهر',
    'مدينة قباء',
    'مدينة بدر'
  ],
  [governorates[1]]: [
    'العجوزه',
    'الدقى',
    'المهندسيين',
    'فيصل',
    'الهرم',
    '6 اكتوبر',
    'كرداسه',
    'العمرانيه',
    'الجيزة',
    'امبابة',
    'شبرامنت',
    'البدراشين',
    'أوسيم',
    'بولاق الدكرور',
    'أطفيح',
    'الوراق',
    'الحوامديه',
    'ارض اللواء',
    'مركز الصف'
  ],
  [governorates[2]]: [
    'السيوف',
    'السلطان حسين',
    'اللبان',
    'كنجى ماريوت',
    'رأس التين',
    'باكوس',
    'طوسون',
    'كرموز',
    'منشية النزهة',
    'المعموره',
    'شدتس',
    'خورشيد',
    'كليوباترا',
    'الرمل',
    'النوباريه',
    'العامريه',
    'ابوقير',
    'فيكتوريا',
    'المنشيه',
    'المكس',
    'برج العرب',
    'العطارين',
    'باب شرق',
    'مينا البصل',
    'سابا باشا',
    'كفر عبدة',
    'زيزينيا',
    'مصطفى كامل',
    'لوران',
    'كامب شيزار',
    'محرم بك',
    'المنتزه',
    'الازاريطة',
    'سيدي جابر',
    'الحضرة الجديدة',
    'الدخيله',
    'ميامي',
    'الهنوفيل',
    'سموحة',
    'العصافرة',
    'جناكليز',
    'سبورتينج',
    'بولكلى',
    'الابراهيمية',
    'سيدي بشر',
    'المندرة',
    'سان ستيفانو',
    'رشدى',
    'الجمرك',
    'محطة الرمل',
    'العجمي',
    'فلمنج',
    'الشاطبى',
    'جليم'
  ],
  [governorates[3]]: [
    'القلج',
    'بهتيم',
    'كفر شكر',
    'ابو زعبل',
    'شبرا الخيمة',
    'شبين القناطر',
    'طوخ',
    'قليوب',
    'الخانكة',
    'بنها',
    'القناطر الخيرية'
  ],
  [governorates[4]]: ['بورسعيد'],
  [governorates[5]]: [
    'العاشر من رمضان',
    'الزقازيق',
    'فاقوس',
    'بلبيس',
    'أبو حماد',
    'منيا القمح',
    'مركز درب نجم',
    'كفر ابراش',
    'مركز الحسنية',
    'مشتول السوق',
    'ههيا',
    'ابو كبير',
    'بسيون'
  ],
  [governorates[6]]: ['الغردقة', 'سفاجا', 'راس غارب', 'القصير', 'مرسى علم', 'شلاتين', 'مدينة حلايب'],
  [governorates[7]]: [
    'قويسنا',
    'السادات',
    'بركة السبع',
    'الشهداء',
    'مركز منوف',
    'اشمون',
    'شبين الكوم',
    'تلا',
    'مركز الباجور'
  ],
  [governorates[8]]: [
    'مركز قوص',
    'مركز قفط',
    'مركز نقادة',
    'مركز قنا',
    'مركزالوقف',
    'مركزأبو تشت',
    'مركز فرشوط',
    'مركز نجع حمادي',
    'مركز دشنا'
  ],
  [governorates[9]]: [
    'أجا',
    'الجمالية',
    'الستاموني',
    'السنبلاوين',
    'الكردي',
    'المطرية',
    'المنزلة',
    'المنصورة',
    'بلقاس',
    'بني عبيد',
    'تمي الأمديد',
    'شربين',
    'طلخا',
    'محلة دمنة',
    'منية النصر',
    'نبروه',
    'ميت غمر',
    'ميت سلسيل'
  ],
  [governorates[10]]: ['الفيوم', 'سنورس', 'إبشواي', 'اطسا', 'طامية', 'يوسف الصديق'],
  [governorates[11]]: ['طنطا', 'كفر الزيات', 'المحلة الكبرى', 'السنطه', 'زفتي', 'قطور', 'بسيون', 'سمنود'],
  [governorates[12]]: ['الواسطى', 'ناصر', 'إهناسيا', 'ببا', 'سمسطا', 'الفشن', 'بني سويف الجديدة', 'بنى سويف'],
  [governorates[13]]: ['الأقصر'],
  [governorates[14]]: ['الاسماعيلية', 'التل الكبير', 'فايد', 'القنطرة شرق', 'القنطرة غرب', 'أبوصوير', 'القصاصين'],
  [governorates[15]]: [
    'نويبع',
    'شرم الشيخ',
    'أبو رديس',
    'أبو زنيمة',
    'طابا',
    'رأس سدر',
    'سانت كاترين',
    'دهب',
    'طور سيناء'
  ],
  [governorates[16]]: [
    'مغاغة',
    'بني مزار',
    'مطاي',
    'سمالوط',
    'مدينة المنيا',
    'أبو قرقاص',
    'ملوي',
    'دير مواس',
    'العدوة  '
  ],
  [governorates[17]]: [
    'مطوبس',
    'فوه',
    'قَلّين',
    'مركز كفر الشيخ',
    'دسوق',
    'بيَلا',
    'الحامول',
    'البُرلُّس',
    'سيدى سالم',
    'مركز الرياض'
  ],
  [governorates[18]]: ['اسوان', 'دراو', 'كوم أمبو', 'نصر النوبة', 'إدفو'],
  [governorates[19]]: [
    'ايتاى البارود',
    'كوم حماده',
    'النوبارية',
    'كفر الدوار',
    'الرحمانية',
    'ابو المطامير',
    'ادكو`',
    'مركز رشيد',
    'كفر الشيخ',
    'مركز بدر',
    'مركز وادى النطرون',
    'دمنهور',
    'حوش عيسى',
    'مركز ابو حمص',
    'شبراخيت',
    'الدلنجات',
    'مركز المحموديه'
  ],
  [governorates[20]]: ['كفر البطيخ', 'الزرقا', 'فارسكور', 'دمياط', 'كفر سعد'],
  [governorates[21]]: ['بئر العبد', 'نخل', 'الحسنة', 'العريش', 'الشيخ زويد', 'رفح'],
  [governorates[22]]: ['حي السويس', 'حي الأربعين', 'حي عتاقة', 'حى الجناين', 'حى فيصل'],
  [governorates[23]]: [
    'مركز سيوة',
    'مركز السلوم',
    'مركز براني',
    'مركز النجيلة',
    'مركز مرسى مطروح',
    'مركز الضبعة',
    'مركز العلمين',
    'مركز الحمام'
  ],
  [governorates[24]]: [
    'البلينا',
    'جرجا',
    'المنشاة',
    'جهينة',
    'طما',
    'طهطا',
    'المراغة',
    'ساقلتة',
    'دارالسلام',
    'أخميم',
    'مركز سوهاج'
  ],
  [governorates[25]]: [
    'ديروط',
    'القوصية',
    'أبنوب',
    'منفلوط',
    'أسيوط',
    'صدفا',
    'البداري',
    'ساحل سليم',
    'أبو تيج',
    'الغنايم'
  ],
  [governorates[26]]: ['الخارجة', 'باريس', 'موط', 'بلاط', 'الفرافرة'],
  [governorates[27]]: ['أخرى']
};
export enum CarConditionEn {
  NEW = 'New',
  OLD = 'Old'
}

export enum CarConditionAr {
  NEW = 'جديد',
  OLD = 'قديم'
}
export enum ProductsEn {
  Auto = 'Auto',
  Shopping = 'Shopping',
  Finishing = 'Finishing',
  Mortgage = 'Mortgage',
  InsuranceBrokerage = 'Insurance Brokerage',
  Leasing = 'Leasing',
  Trucks = 'Trucks'
}

export enum ProductsAr {
  Auto = 'تمويل السيارات',
  Shopping = 'تسوق',
  Finishing = 'تمويل التشطيب',
  Mortgage = 'تمويل عقاري',
  InsuranceBrokerage = 'وساطة تأمينية',
  Leasing = 'تأجير تمويلي',
  Trucks = 'تمويل النقل'
}

export enum TruckConditionEn {
  NEW = 'Heavy',
  OLD = 'Light'
}

export enum TruckConditionAr {
  NEW = 'ثقيل',
  OLD = 'خفيف'
}

export const englishBrands = [
  'MG',
  'Opel',
  'Audi',
  'Aston Martin',
  'Alfa Romeo',
  'Proton',
  'Bralience',
  'Porche',
  'BMW',
  'BYD',
  'Peugeot',
  'Toyota',
  'Jaguar',
  'Jac',
  'Jeep',
  'DS',
  'Range Rover',
  'Renault',
  'Sang Yong',
  'Citroene',
  'Scoda',
  'Subaru',
  'Suzuki',
  'Seat',
  'Shangan',
  'Cherry',
  'Chevrolet',
  'Ford',
  'Volvo',
  'Volkes Wagen',
  'Fiat',
  'Chrysler',
  'Kia',
  'Lada',
  'Land Rover',
  'Luxus',
  'Mazda',
  'Mazarati',
  'Mitsubishi',
  'Mercedes',
  'Mini',
  'Nissan',
  'Honda',
  'Hyundai'
];

export const arabicBrands = [
  'أم جي',
  'اوبل',
  'اودي',
  'استون مارتن',
  'الفا روميو',
  'بروتون',
  'برليانس',
  'بورش',
  'بي ام دابليو',
  'بي واي دي',
  'بيجو',
  'تويوتا',
  'جاجوار',
  'جاك',
  'جيب',
  'دي اس',
  'رانج روفر',
  'رينو',
  'سنج يونج',
  'سيتروين',
  'سكودا',
  'سوبارو',
  'سوزوكي',
  'سيات',
  'شانجان',
  'شيرى',
  'شفروليه',
  'فورد',
  'فولفو',
  'فولكس فاجن',
  'فيات',
  'كرايسلر',
  'كيا',
  'لادا',
  'لاند روفر',
  'لاكسس',
  'مازدا',
  'مازاراتي',
  'ميسوبيشي',
  'مارسيدس',
  'ميني',
  'نيسان',
  'هوندا',
  'هيونداي'
];
